// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uptime.Auction.Web.Repositories;

namespace Uptime.Auction.Web.Migrations
{
    [DbContext(typeof(AuctionContext))]
    [Migration("20180706104235_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Uptime.Auction.Core.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CurrentPrice");

                    b.Property<DateTime>("End");

                    b.Property<string>("Item");

                    b.Property<DateTime>("Start");

                    b.Property<double>("StartingPrice");

                    b.HasKey("Id");

                    b.ToTable("Auction");
                });
#pragma warning restore 612, 618
        }
    }
}
